/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  PBMBaseErrors,
  PBMBaseErrorsInterface,
} from "../../../contracts/interfaces/PBMBaseErrors";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "AutoWithdrawalUnsupported",
    type: "error",
  },
] as const;

export class PBMBaseErrors__factory {
  static readonly abi = _abi;
  static createInterface(): PBMBaseErrorsInterface {
    return new utils.Interface(_abi) as PBMBaseErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PBMBaseErrors {
    return new Contract(address, _abi, signerOrProvider) as PBMBaseErrors;
  }
}
