/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  PBMTaskManagerErrors,
  PBMTaskManagerErrorsInterface,
} from "../../../contracts/interfaces/PBMTaskManagerErrors";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "CallerNotFundsOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "TaskCallerNotPBM",
    type: "error",
  },
  {
    inputs: [],
    name: "TaskExists",
    type: "error",
  },
  {
    inputs: [],
    name: "UnauthorisedCaller",
    type: "error",
  },
] as const;

export class PBMTaskManagerErrors__factory {
  static readonly abi = _abi;
  static createInterface(): PBMTaskManagerErrorsInterface {
    return new utils.Interface(_abi) as PBMTaskManagerErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PBMTaskManagerErrors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PBMTaskManagerErrors;
  }
}
