/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  PBMVaultBaseErrors,
  PBMVaultBaseErrorsInterface,
} from "../../../contracts/interfaces/PBMVaultBaseErrors";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "CallerNotPBM",
    type: "error",
  },
] as const;

export class PBMVaultBaseErrors__factory {
  static readonly abi = _abi;
  static createInterface(): PBMVaultBaseErrorsInterface {
    return new utils.Interface(_abi) as PBMVaultBaseErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PBMVaultBaseErrors {
    return new Contract(address, _abi, signerOrProvider) as PBMVaultBaseErrors;
  }
}
