/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  PBMVaultErrors,
  PBMVaultErrorsInterface,
} from "../../../contracts/interfaces/PBMVaultErrors";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "CallerNotPBM",
    type: "error",
  },
] as const;

export class PBMVaultErrors__factory {
  static readonly abi = _abi;
  static createInterface(): PBMVaultErrorsInterface {
    return new utils.Interface(_abi) as PBMVaultErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PBMVaultErrors {
    return new Contract(address, _abi, signerOrProvider) as PBMVaultErrors;
  }
}
