/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAutomate } from "./IAutomate";
export type { ITaskTreasuryUpgradable } from "./ITaskTreasuryUpgradable";
