/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface IPBMTaskManagerInterface extends utils.Interface {
  functions: {
    "cancelWithdrawalTask(uint256)": FunctionFragment;
    "createWithdrawalTask(address,uint256)": FunctionFragment;
    "execWithdrawal(address,uint256)": FunctionFragment;
    "getTaskId(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cancelWithdrawalTask"
      | "createWithdrawalTask"
      | "execWithdrawal"
      | "getTaskId"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancelWithdrawalTask",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createWithdrawalTask",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "execWithdrawal",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelWithdrawalTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createWithdrawalTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTaskId", data: BytesLike): Result;

  events: {
    "WithdrawalTaskCancelled(bytes32,uint256)": EventFragment;
    "WithdrawalTaskCreated(bytes32,address,uint256)": EventFragment;
    "WithdrawalTaskExecution(bytes32,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "WithdrawalTaskCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalTaskCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalTaskExecution"): EventFragment;
}

export interface WithdrawalTaskCancelledEventObject {
  taskId: string;
  depositId: BigNumber;
}
export type WithdrawalTaskCancelledEvent = TypedEvent<
  [string, BigNumber],
  WithdrawalTaskCancelledEventObject
>;

export type WithdrawalTaskCancelledEventFilter =
  TypedEventFilter<WithdrawalTaskCancelledEvent>;

export interface WithdrawalTaskCreatedEventObject {
  taskId: string;
  payee: string;
  depositId: BigNumber;
}
export type WithdrawalTaskCreatedEvent = TypedEvent<
  [string, string, BigNumber],
  WithdrawalTaskCreatedEventObject
>;

export type WithdrawalTaskCreatedEventFilter =
  TypedEventFilter<WithdrawalTaskCreatedEvent>;

export interface WithdrawalTaskExecutionEventObject {
  taskId: string;
  success: boolean;
}
export type WithdrawalTaskExecutionEvent = TypedEvent<
  [string, boolean],
  WithdrawalTaskExecutionEventObject
>;

export type WithdrawalTaskExecutionEventFilter =
  TypedEventFilter<WithdrawalTaskExecutionEvent>;

export interface IPBMTaskManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPBMTaskManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancelWithdrawalTask(
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createWithdrawalTask(
      payee: PromiseOrValue<string>,
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    execWithdrawal(
      payee: PromiseOrValue<string>,
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getTaskId(
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  cancelWithdrawalTask(
    depositId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createWithdrawalTask(
    payee: PromiseOrValue<string>,
    depositId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  execWithdrawal(
    payee: PromiseOrValue<string>,
    depositId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getTaskId(
    depositId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    cancelWithdrawalTask(
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createWithdrawalTask(
      payee: PromiseOrValue<string>,
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    execWithdrawal(
      payee: PromiseOrValue<string>,
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getTaskId(
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "WithdrawalTaskCancelled(bytes32,uint256)"(
      taskId?: PromiseOrValue<BytesLike> | null,
      depositId?: PromiseOrValue<BigNumberish> | null
    ): WithdrawalTaskCancelledEventFilter;
    WithdrawalTaskCancelled(
      taskId?: PromiseOrValue<BytesLike> | null,
      depositId?: PromiseOrValue<BigNumberish> | null
    ): WithdrawalTaskCancelledEventFilter;

    "WithdrawalTaskCreated(bytes32,address,uint256)"(
      taskId?: PromiseOrValue<BytesLike> | null,
      payee?: PromiseOrValue<string> | null,
      depositId?: PromiseOrValue<BigNumberish> | null
    ): WithdrawalTaskCreatedEventFilter;
    WithdrawalTaskCreated(
      taskId?: PromiseOrValue<BytesLike> | null,
      payee?: PromiseOrValue<string> | null,
      depositId?: PromiseOrValue<BigNumberish> | null
    ): WithdrawalTaskCreatedEventFilter;

    "WithdrawalTaskExecution(bytes32,bool)"(
      taskId?: PromiseOrValue<BytesLike> | null,
      success?: PromiseOrValue<boolean> | null
    ): WithdrawalTaskExecutionEventFilter;
    WithdrawalTaskExecution(
      taskId?: PromiseOrValue<BytesLike> | null,
      success?: PromiseOrValue<boolean> | null
    ): WithdrawalTaskExecutionEventFilter;
  };

  estimateGas: {
    cancelWithdrawalTask(
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createWithdrawalTask(
      payee: PromiseOrValue<string>,
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    execWithdrawal(
      payee: PromiseOrValue<string>,
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getTaskId(
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cancelWithdrawalTask(
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createWithdrawalTask(
      payee: PromiseOrValue<string>,
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    execWithdrawal(
      payee: PromiseOrValue<string>,
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getTaskId(
      depositId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
