/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as erc20 from "./ERC20";
import type * as erc721 from "./ERC721";
import type * as erc777 from "./ERC777";
import type * as erc1155 from "./ERC1155";

export type { erc1155 };

export type { erc20 };

export type { erc721 };

export type { erc777 };
