/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { PromiseOrValue } from "../../../common";
import type {
  MockPBMTaskManagerRevert,
  MockPBMTaskManagerRevertInterface,
} from "../../../contracts/mocks/MockPBMTaskManagerRevert";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "CallerNotFundsOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "FakeError",
    type: "error",
  },
  {
    inputs: [],
    name: "TaskCallerNotPBM",
    type: "error",
  },
  {
    inputs: [],
    name: "TaskExists",
    type: "error",
  },
  {
    inputs: [],
    name: "UnauthorisedCaller",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    name: "WithdrawalTaskExecution",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "cancelWithdrawalTask",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "createWithdrawalTask",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "execWithdrawal",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getTaskId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061015d806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630baddc9a14610051578063cd5a3b7014610079578063d44bc0881461008e578063ec122d0a146100b0575b600080fd5b61006461005f3660046100f2565b6100be565b60405190151581526020015b60405180910390f35b61008c6100873660046100f2565b6100d9565b005b6100a261009c366004610137565b50600090565b604051908152602001610070565b61006461005f366004610137565b60006040516372ce7a0760e11b815260040160405180910390fd5b6040516372ce7a0760e11b815260040160405180910390fd5b6000806040838503121561010557600080fd5b823573ffffffffffffffffffffffffffffffffffffffff8116811461012957600080fd5b946020939093013593505050565b60006020828403121561014957600080fd5b503591905056fea164736f6c6343000813000a";

type MockPBMTaskManagerRevertConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockPBMTaskManagerRevertConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockPBMTaskManagerRevert__factory extends ContractFactory {
  constructor(...args: MockPBMTaskManagerRevertConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MockPBMTaskManagerRevert> {
    return super.deploy(overrides || {}) as Promise<MockPBMTaskManagerRevert>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MockPBMTaskManagerRevert {
    return super.attach(address) as MockPBMTaskManagerRevert;
  }
  override connect(signer: Signer): MockPBMTaskManagerRevert__factory {
    return super.connect(signer) as MockPBMTaskManagerRevert__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockPBMTaskManagerRevertInterface {
    return new utils.Interface(_abi) as MockPBMTaskManagerRevertInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockPBMTaskManagerRevert {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MockPBMTaskManagerRevert;
  }
}
