/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITimeLockVault } from "./ITimeLockVault";
export type { TimeLockVaultErrors } from "./TimeLockVaultErrors";
