/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as gelatoAutomate from "./gelato-automate";
import type * as proxy from "./proxy";

export type { gelatoAutomate };

export type { proxy };
