name: Build Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - staging
      - production
    paths:
      - "packages/web/**"
      - "yarn.lock"

defaults:
  run:
    working-directory: packages/web

jobs:
  deploy:
    name: Test Build for Website Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: ${{ github.workspace }}
        env:
          ECR_REPOSITORY: test/website-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            --build-arg BASE_URL=http://localhost \
            --build-arg UX_FEATURE_DECK_URL=http://localhost/deck \
            -f packages/web/Dockerfile -t $ECR_REPOSITORY:$IMAGE_TAG .
